### ISSUE TITLE
tar funzt net mit symlinks

### ISSUE THREAD

**Issue by unclesamwk** [hermsicodes/bash-backup#1]
Hey Dennis,

Zeile 62 anpassen:
${USE_TAR} -chjvfz "${ARCHIV}" "${src}" &>>${TMPLOG}

Dann folgt der tar auch symlinks.

Gruß

Sam

**Comment by hermsicodes** [comment]
Hey Sam,

danke für deinen Tipp (:

Ist im commit 3b3eb8fb3824b5dcf94639323167e40d83663ede eingebaut:
https://github.com/hermsicodes/bash-backup/commit/3b3eb8fb3824b5dcf94639323167e40d83663ede

Gruß <3
Hermsi
